name: crypto_tracker
description: "This Flutter application allows users to track their cryptocurrency portfolio, compare cryptocurrencies side-by-side, and view key metrics and trends. The app integrates with a public cryptocurrency API to fetch live data"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  intl: ^0.18.1
  retrofit: ^4.1.0
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.10
  dio: ^5.4.1
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  calendar_date_picker2: ^0.5.3
  dropdown_button2: ^2.3.9
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  auto_route_generator: ^7.3.2
  riverpod_lint: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: RosaSans
      fonts:
        - asset: assets/fonts/RosaSans-Black.ttf
          weight: 800
        - asset: assets/fonts/RosaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/RosaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RosaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/RosaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/RosaSans-Light.ttf
          weight: 300
    - family: bicons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
